/**
 * Security Header Auto-Fix Module
 * 
 * When EdgeIQ headers-checker detects missing security headers,
 * this module deploys a Cloudflare Worker to add recommended headers.
 * 
 * Headers deployed:
 * - Strict-Transport-Security (HSTS)
 * - X-Content-Type-Options
 * - X-Frame-Options
 * - X-XSS-Protection
 * - Content-Security-Policy
 * - Referrer-Policy
 * - Permissions-Policy
 */

// Recommended security headers configuration
const RECOMMENDED_HEADERS = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-XSS-Protection': '1; mode=block',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
};

// Content Security Policy (strict but functional)
const CSP_TEMPLATE = {
  defaultSrc: "'self'",
  scriptSrc: "'self' 'unsafe-inline'",
  styleSrc: "'self' 'unsafe-inline'",
  imgSrc: "'self' data: https:",
  fontSrc: "'self'",
  connectSrc: "'self'",
  frameSrc: "'none'",
  objectSrc: "'none'",
};

/**
 * Build CSP header value from template
 */
function buildCSP(customCSP = {}) {
  const csp = { ...CSP_TEMPLATE, ...customCSP };
  
  const parts = [];
  for (const [directive, value] of Object.entries(csp)) {
    parts.push(`${directive} ${value}`);
  }
  
  return parts.join('; ');
}

/**
 * Execute security header fix for a target domain
 * @param {Object} target - Target configuration { domain, cfZoneId }
 * @param {Object} options - Additional options { headers, workerName, csp }
 * @param {Object} env - Environment bindings
 */
export async function execute(target, options = {}, env) {
  const { domain, cfZoneId, customerId } = target;
  
  if (!domain) {
    return { success: false, error: 'Domain is required' };
  }

  // Get customer config if customerId provided
  let cfApiToken = options.cfApiToken;
  let zoneId = cfZoneId || options.cfZoneId;

  if (customerId && env.CUSTOMER_CONFIG && !cfApiToken) {
    const configStr = await env.CUSTOMER_CONFIG.get(`customer:${customerId}`);
    if (configStr) {
      const config = JSON.parse(configStr);
      cfApiToken = config.cfApiToken;
      zoneId = zoneId || config.cfZoneId;
    }
  }

  // Fall back to EdgeIQ's own Cloudflare token
  cfApiToken = cfApiToken || env.CLOUDFLARE_API_TOKEN;
  zoneId = zoneId || env.CLOUDFLARE_ZONE_ID;

  if (!cfApiToken) {
    return { success: false, error: 'No Cloudflare API token available' };
  }

  if (!zoneId) {
    return { success: false, error: 'No Cloudflare Zone ID available' };
  }

  const workerName = options.workerName || `edgeiq-security-headers-${domain.replace(/\./g, '-')}`;
  const customHeaders = options.headers || {};
  const cspValue = options.csp || buildCSP(options.cspConfig);

  try {
    // Step 1: Create the security headers worker script
    const workerScript = generateWorkerScript({
      ...customHeaders,
      'Content-Security-Policy': cspValue,
    });

    // Step 2: Check if worker already exists
    const existingWorker = await getWorker(workerName, zoneId, cfApiToken);

    // Step 3: Upload/update the worker
    const uploadResult = await uploadWorker(workerName, workerScript, zoneId, cfApiToken);

    // Step 4: Route traffic through the worker (create a route)
    const routeResult = await createRoute(domain, workerName, zoneId, cfApiToken);

    return {
      success: true,
      action: existingWorker ? 'updated' : 'created',
      domain,
      workerName,
      headersAdded: Object.keys(RECOMMENDED_HEADERS).length + 1, // +1 for CSP
      headers: Object.keys({ ...RECOMMENDED_HEADERS, 'Content-Security-Policy': cspValue }),
      routeId: routeResult.routeId,
      workerScriptId: uploadResult.scriptId,
    };

  } catch (error) {
    console.error(`Header fix failed for ${domain}:`, error);
    return {
      success: false,
      error: error.message,
      domain,
    };
  }
}

/**
 * Generate the Cloudflare Worker script that adds security headers
 */
function generateWorkerScript(customHeaders = {}) {
  const headers = { ...RECOMMENDED_HEADERS, ...customHeaders };
  const cspValue = headers['Content-Security-Policy'] || buildCSP();
  
  // Remove CSP from headers object since we handle it specially
  const { 'Content-Security-Policy': _, ...staticHeaders } = headers;

  return `/**
 * EdgeIQ Security Headers Worker
 * Auto-generated by EdgeIQ Autopilot Security
 * 
 * Adds recommended security headers to all responses.
 * 
 * Headers applied:
${Object.keys(staticHeaders).map(h => ` * - ${h}`).join('\n')}
 * - Content-Security-Policy (customizable)
 */

export default {
  async fetch(request) {
    // Clone the response to modify headers
    const response = await fetch(request);
    
    // Create new headers object with security headers added
    const newHeaders = new Headers(response.headers);
    
    // Add security headers
${Object.entries(staticHeaders).map(([name, value]) => 
      `    newHeaders.set('${name}', '${value}');`
    ).join('\n')}
    
    // Add Content-Security-Policy (set separately due to complexity)
    newHeaders.set('Content-Security-Policy', ${JSON.stringify(cspValue)});
    
    // Return modified response
    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers: newHeaders,
    });
  },
};`;
}

/**
 * Get existing worker info
 */
async function getWorker(workerName, zoneId, apiToken) {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${env.CLOUDFLARE_ACCOUNT_ID || 'account'}/workers/scripts/${workerName}`,
    {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${apiToken}`,
      },
    }
  );

  if (response.ok) {
    const data = await response.json();
    return data;
  }

  return null;
}

/**
 * Upload worker script to Cloudflare
 */
async function uploadWorker(workerName, script, zoneId, apiToken) {
  const accountId = env.CLOUDFLARE_ACCOUNT_ID;

  if (!accountId) {
    throw new Error('CLOUDFLARE_ACCOUNT_ID is required for worker deployment');
  }

  // Use Workers Script Upload endpoint
  const formData = new FormData();
  formData.append('script', new Blob([script], { type: 'application/javascript' }));
  formData.append('metadata', JSON.stringify({ body_part: 'script' }));

  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/${workerName}`,
    {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${apiToken}`,
      },
      body: formData,
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to upload worker: ${response.status} ${errorText}`);
  }

  const data = await response.json();
  return {
    scriptId: data.script?.id || workerName,
    scriptName: data.script?.name || workerName,
  };
}

/**
 * Create a route to apply the worker to a domain
 */
async function createRoute(domain, workerName, zoneId, apiToken) {
  const accountId = env.CLOUDFLARE_ACCOUNT_ID;

  // First, get existing routes to check for conflicts
  const routesResponse = await fetch(
    `https://api.cloudflare.com/client/v4/zones/${zoneId}/workers/routes`,
    {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${apiToken}`,
      },
    }
  );

  let routeId = null;

  if (routesResponse.ok) {
    const routesData = await routesResponse.json();
    const existingRoute = routesData.result?.find(
      r => r.pattern === `*${domain}/*` || r.pattern === `${domain}/*`
    );
    
    if (existingRoute) {
      routeId = existingRoute.id;
    }
  }

  // Create or update route
  const routePattern = `*${domain}/*`;
  
  const routeData = {
    pattern: routePattern,
    script: workerName,
  };

  let routeResponse;

  if (routeId) {
    // Update existing route
    routeResponse = await fetch(
      `https://api.cloudflare.com/client/v4/zones/${zoneId}/workers/routes/${routeId}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${apiToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(routeData),
      }
    );
  } else {
    // Create new route
    routeResponse = await fetch(
      `https://api.cloudflare.com/client/v4/zones/${zoneId}/workers/routes`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(routeData),
      }
    );
  }

  if (!routeResponse.ok) {
    const errorText = await routeResponse.text();
    // If routes API not available (older account), that's OK - worker still works
    if (!errorText.includes('workers_routes')) {
      throw new Error(`Failed to create route: ${response.status} ${errorText}`);
    }
  }

  const routeResult = await routeResponse.json();
  
  return {
    routeId: routeResult.result?.id || routeId,
    pattern: routePattern,
  };
}

/**
 * Remove security headers from a domain (cleanup)
 */
export async function remove(domain, customerId, env) {
  const target = { domain, customerId };
  const result = await execute(target, { remove: true }, env);
  
  return {
    ...result,
    action: 'removed',
  };
}

/**
 * Get current security headers on a domain (analysis only)
 */
export async function analyze(domain, customerId, env) {
  // This would typically call the existing EdgeIQ headers-checker
  // For now, return a stub that could call out to the checker
  return {
    domain,
    headers: RECOMMENDED_HEADERS,
    csp: buildCSP(),
    note: 'Full analysis requires calling edgeiq-headers-checker',
  };
}

export const moduleInfo = {
  name: 'Security Header Auto-Fix',
  version: '1.0.0',
  description: 'Deploy recommended security headers via Cloudflare Workers',
  headers: Object.keys(RECOMMENDED_HEADERS),
};